### PR TITLE
Add schema and samples

### PR DESCRIPTION
**Pull request by masihyeganeh**
This change is [Reviewable](https://reviewable.io/reviews/CoreumFoundation/iso20022-addressbook/1)

### CODE REVIEW

**Review by miladz68 — CHANGES_REQUESTED** [review]
> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/iso20022-addressbook/1)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @masihyeganeh, @wojtek-coreum, and @ysv)

___
*[`.github/workflows/validate.yml` line 24 at r1](https://reviewable.io/reviews/coreumfoundation/iso20022-addressbook/1#-O0TPZbLDKAmowN-mbXn:-O0TPZbM3UeNp6HY6Rib:b4iarmf) ([raw file](https://github.com/coreumfoundation/iso20022-addressbook/blob/f61f1fcaf3d2c5e252eb203df26cc9c61b566cef/.github/workflows/validate.yml#L24)):*
> ```YAML
>         run: go build -v ./...
>       - name: Validate data
>         uses: robherley/go-test-action@v0
> ```

I mentioned that probably having a repository is not a good idea. but if we decide to go this route, we need much more than just json validation and we should write own own validation function.
___
*[`coreum-mainnet-1/addressbook.json` line 2 at r1](https://reviewable.io/reviews/coreumfoundation/iso20022-addressbook/1#-O0TPA-26RzPCLDuMN6b:-O0TPA-26RzPCLDuMN6c:bwpsj3s) ([raw file](https://github.com/coreumfoundation/iso20022-addressbook/blob/f61f1fcaf3d2c5e252eb203df26cc9c61b566cef/coreum-mainnet-1/addressbook.json#L2)):*
> ```JSON
> {
>     "$schema": "../addressbook.schema.json",
> ```

mainnet should be empty since it is real and final.

**Review by masihyeganeh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/iso20022-addressbook/1)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

___
*[`.github/workflows/validate.yml` line 24 at r1](https://reviewable.io/reviews/coreumfoundation/iso20022-addressbook/1#-O0TPZbLDKAmowN-mbXn:-O0hnp2KCty9pUrAKDWi:bx9gtri) ([raw file](https://github.com/coreumfoundation/iso20022-addressbook/blob/f61f1fcaf3d2c5e252eb203df26cc9c61b566cef/.github/workflows/validate.yml#L24)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I mentioned that probably having a repository is not a good idea. but if we decide to go this route, we need much more than just json validation and we should write own own validation function.
</blockquote></details>

We already have it

**Review by miladz68 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/iso20022-addressbook/1)* status: all files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @masihyeganeh, @wojtek-coreum, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/iso20022-addressbook/1#-O0mlzmo0c_rBKynRfec:-O0mlzmpDPlMbgO_ug7K:bok52jh) (no related file):*
rename main branch to master, we have done so for every other repo.

___

**Review by masihyeganeh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/iso20022-addressbook/1)* status: 6 of 11 files reviewed, 2 unresolved discussions (waiting on @dzmitryhil, @miladz68, @wojtek-coreum, and @ysv)

*[a discussion](https://reviewable.io/reviews/coreumfoundation/iso20022-addressbook/1#-O0mlzmo0c_rBKynRfec:-O0syiLACs-hOdwAoJpd:b-896fix) (no related file):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

rename main branch to master, we have done so for every other repo.
</blockquote></details>

Done.

___
___
*[`coreum-mainnet-1/addressbook.json` line 2 at r1](https://reviewable.io/reviews/coreumfoundation/iso20022-addressbook/1#-O0TPA-26RzPCLDuMN6b:-O0syjiT8puOQAddKz0O:b-896fix) ([raw file](https://github.com/coreumfoundation/iso20022-addressbook/blob/f61f1fcaf3d2c5e252eb203df26cc9c61b566cef/coreum-mainnet-1/addressbook.json#L2)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

mainnet should be empty since it is real and final.
</blockquote></details>

Done.

**Review by miladz68 — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/iso20022-addressbook/1#-:-O0xmrLT6rRRvRpQJBqu:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

**Review by masihyeganeh — COMMENTED** [review]
> Reviewed 4 of 11 files at r1, 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/coreumfoundation/iso20022-addressbook/1)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dzmitryhil, @wojtek-coreum, and @ysv)

**Pull request merged**
